# Momentum Strategy Configuration File
# All parameters can be overridden via API query parameters

# Portfolio Settings
capital: 500000          # Total capital in INR
top_n: 15               # Number of top stocks to select
price_cap: 3000         # Maximum price per share in INR (set to null to disable)

# Stock Universe Source
universe_source: "https://archives.nseindia.com/content/indices/ind_nifty500list.csv"

# Strategy Parameters (in trading days)
history_days: 400        # Total price history to download
lookback_6m_days: 126    # ~6 months of trading days
lookback_12m_days: 252   # ~12 months of trading days
exclude_1m_days: 21      # Exclude last 1 month for momentum calc
vol_window_days: 63      # ~3 months for volatility calculation
sma_window_days: 200     # 200-day simple moving average

# Output Settings
output_dir: "output"     # Directory to save CSV files
write_csv: true          # Enable CSV output
tz: "Asia/Kolkata"       # Timezone for date calculations

# Optional Filters (can be set via API parameters)
# min_momentum_score: 1.0  # Minimum momentum score filter
# max_volatility: 40.0     # Maximum volatility filter (%)

# Risk Management (for /levels endpoint)
atr_period: 14           # ATR calculation period
stop_multipliers:        # ATR multipliers for stops/targets
  conservative_stop: 2.0
  aggressive_stop: 1.5
  target: 2.0

# Data Quality Settings
min_data_coverage: 0.6   # Minimum % of data points required
max_fill_days: 5         # Max days to forward fill missing data

# Performance Settings
download_batch_size: 100 # Tickers per batch for yfinance
max_retries: 3          # Retry attempts for failed downloads
request_delay: 0.1      # Delay between requests (seconds)

# Volume Filters
min_avg_turnover_cr: 10.0   # require ₹10 Cr average daily turnover over last 60 sessions
min_avg_volume: 10000       # Minimum average daily volume
